name: covtrack
description: CovTrack is a mobile app to help against Covid-19 pandemic
version: 1.0.0+1
environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Firebase NoSQL database. 
  cloud_firestore:
  # App localization.
  flutter_localizations:
    sdk: flutter
  # Compare objects not references.
  equatable:
  # Firebase Authentication API.
  firebase_auth:
  # Firebase Core Flutter SDK.
  firebase_core:
  # Firebase Remote Config API.
  firebase_remote_config:
  # BLoC pattern utilities.
  flutter_bloc:
  # Autocomplete TextField.
  flutter_typeahead:
  # Font Awesome icon pack.
  font_awesome_flutter:
  # Device location.
  geolocator:
  # Google Maps.
  google_maps_flutter:
  # Google Maps APIs wrapper.
  google_maps_webservice:
  # Authentication with Google.
  google_sign_in:
  # HTTP client for making requests.
  http:
  # Internationalization and localization.
  intl:
  intl_translation:
  # Onboarding.
  introduction_screen:
  # Reactive programming.
  rxdart:
  # QR code rendering.
  qr_flutter:
  # Shared preferences.
  shared_preferences:
  # Launching a URL in the mobile platform.
  url_launcher:
  # Generate RFC4122 UUIDs.
  uuid:


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Mocking facilities for testing.
  mockito:
  # Testing BLoCs.
  bloc_test:
  

flutter:
  uses-material-design: true
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Light.ttf
          weight: 300
        - asset: fonts/Prompt-Regular.ttf
          weight: 400
        - asset: fonts/Prompt-Medium.ttf
          weight: 500
        - asset: fonts/Prompt-SemiBold.ttf
          weight: 600
        - asset: fonts/Prompt-Bold.ttf
          weight: 700
        - asset: fonts/Prompt-ExtraBold.ttf
          weight: 800
        - asset: fonts/Prompt-Black.ttf
          weight: 900
